# Generated by Django 6.0.2 on 2026-02-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scrobble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('musicbrainz_id', models.CharField(max_length=36)),
                ('user_id', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('preferred_username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
