# Generated by Django 6.0.2 on 2026-02-25 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='preferred_username',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
