# Generated by Django 6.0.2 on 2026-04-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_song_recommendations_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuttiuser',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tuttiuser',
            name='country',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
